# List of settings and ignore or safelist findings for the hadolint scanner
# For more information on any settings you can specify, see the actions' documentation here
# https://github.com/hadolint/hadolint#configure
failure-threshold: warning
ignored: []
override:
  info: 
    # Casts the apt-get install <package>=<version> finding as info
    # We have this set since there is no way to specify version for
    #  build-essentials in the Dockerfile
    - DL3008
