info:
  title: Template Application Flask
  description: Template API for a Flask Application
  contact:
    name: Nava PBC Engineering
    url: https://www.navapbc.com
    email: engineering@navapbc.com
  version: 0.1.0
tags:
- name: Health
- name: User
paths:
  /health:
    get:
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status_code:
                    type: integer
                    default: 200
                  warnings:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValidationErrorDetail'
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValidationErrorDetail'
                  data:
                    $ref: '#/components/schemas/HealthOut'
                required:
                - message
          description: Successful response
      tags:
      - Health
      summary: Health
  /v1/user:
    post:
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status_code:
                    type: integer
                    default: 200
                  warnings:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValidationErrorDetail'
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValidationErrorDetail'
                  data:
                    $ref: '#/components/schemas/UserOut'
                required:
                - message
          description: Successful response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: Validation error
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Authentication error
      tags:
      - User
      summary: POST /v1/user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserIn'
      security:
      - ApiKeyAuth: []
  /v1/user/{user_id}:
    get:
      parameters:
      - in: path
        name: user_id
        schema:
          type: string
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status_code:
                    type: integer
                    default: 200
                  warnings:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValidationErrorDetail'
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValidationErrorDetail'
                  data:
                    $ref: '#/components/schemas/UserOut'
                required:
                - message
          description: Successful response
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Authentication error
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Not found
      tags:
      - User
      summary: User Get
      security:
      - ApiKeyAuth: []
    patch:
      parameters:
      - in: path
        name: user_id
        schema:
          type: string
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status_code:
                    type: integer
                    default: 200
                  warnings:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValidationErrorDetail'
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValidationErrorDetail'
                  data:
                    $ref: '#/components/schemas/UserOut'
                required:
                - message
          description: Successful response
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          description: Validation error
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Authentication error
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPError'
          description: Not found
      tags:
      - User
      summary: User Patch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserPatchParams'
      security:
      - ApiKeyAuth: []
openapi: 3.0.3
components:
  schemas:
    ValidationErrorDetail:
      type: object
      properties:
        message:
          type: string
          default: ''
        type:
          type: string
        value:
          type: string
          default: null
          nullable: true
        field:
          type: string
          default: null
          nullable: true
        rule:
          type: string
          default: null
          nullable: true
      required:
      - type
    ValidationError:
      properties:
        detail:
          type: object
          properties:
            <location>:
              type: object
              properties:
                <field_name>:
                  type: array
                  items:
                    type: string
        message:
          type: string
      type: object
    HTTPError:
      properties:
        detail:
          type: object
        message:
          type: string
      type: object
    HealthOut:
      type: object
      properties: {}
    RoleIn:
      type: object
      properties:
        role_description:
          type: string
          description: The name of the role
    UserIn:
      type: object
      properties:
        is_active:
          type: boolean
          description: Whether the user is active
        last_name:
          type: string
          description: The user's last name
        middle_name:
          type: string
          description: The user's middle name
        phone_number:
          type: string
          description: The user's phone number
          example: 123-456-7890
          pattern: ^([0-9]|\*){3}\-([0-9]|\*){3}\-[0-9]{4}$
        roles:
          type: array
          items:
            $ref: '#/components/schemas/RoleIn'
        date_of_birth:
          type: string
          format: date
          description: The users date of birth
        first_name:
          type: string
          description: The user's first name
    RoleOut:
      type: object
      properties:
        created_at:
          type: string
          format: date-time
        role_description:
          type: string
          description: The name of the role
        updated_at:
          type: string
          format: date-time
    UserOut:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
          description: The user's unique identifier
        is_active:
          type: boolean
          description: Whether the user is active
        last_name:
          type: string
          description: The user's last name
        middle_name:
          type: string
          description: The user's middle name
        phone_number:
          type: string
          description: The user's phone number
          example: 123-456-7890
          pattern: ^([0-9]|\*){3}\-([0-9]|\*){3}\-[0-9]{4}$
        roles:
          type: array
          items:
            $ref: '#/components/schemas/RoleOut'
        date_of_birth:
          type: string
          format: date
          description: The users date of birth
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        first_name:
          type: string
          description: The user's first name
    UserPatchParams:
      type: object
      properties:
        is_active:
          type: boolean
          description: Whether the user is active
        last_name:
          type: string
          description: The user's last name
        middle_name:
          type: string
          description: The user's middle name
        phone_number:
          type: string
          description: The user's phone number
          example: 123-456-7890
          pattern: ^([0-9]|\*){3}\-([0-9]|\*){3}\-[0-9]{4}$
        roles:
          type: array
          items:
            $ref: '#/components/schemas/RoleIn'
        date_of_birth:
          type: string
          format: date
          description: The users date of birth
        first_name:
          type: string
          description: The user's first name
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-Auth

