# run with `docker compose -f`
# combines ports and env vars with the main docker-compose.yml main-app service
services:
  main-app:
    build:
      context: ./
      target: dev
      args:
        - RUN_UID=${RUN_UID:-4000}
        - RUN_USER=${RUN_USER:-app}
    container_name: main-app
    env_file: local.env
    command: [
      "poetry", "run", "python", "-m", "debugpy",
      "--listen", "0.0.0.0:5678",
      "--wait-for-client",  "--log-to-stderr",
      "-m", "flask", "--app", "src.app", "run",
      "--host", "0.0.0.0", "--port", "8080", "--no-reload"
    ]
    ports:
      - 5678:5678
    volumes:
      - ./:/app
