"""add another enum val

Revision ID: 389e7f257581
Revises: f9e1862f9c52
Create Date: 2022-09-21 13:21:15.356127

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "389e7f257581"
down_revision = "f9e1862f9c52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "roleenum",
        ["ADMIN", "THIRD_PARTY", "USER"],
        ["ADMIN", "FOURTH_ONE", "THIRD_PARTY", "USER"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "roleenum",
        ["ADMIN", "FOURTH_ONE", "THIRD_PARTY", "USER"],
        ["ADMIN", "THIRD_PARTY", "USER"],
    )
    # ### end Alembic commands ###
