"""lookupenum

Revision ID: 98c3b8dbdeac
Revises: 9fe657340f70
Create Date: 2023-03-17 10:35:06.725206

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "98c3b8dbdeac"
down_revision = "9fe657340f70"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lk_role",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("role_id", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("role_id", name=op.f("lk_role_pkey")),
    )
    op.alter_column(
        "role", "type", existing_type=sa.VARCHAR(length=5), type_=sa.Text(), existing_nullable=False
    )
    op.create_foreign_key(op.f("role_type_lk_role_fkey"), "role", "lk_role", ["type"], ["role_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("role_type_lk_role_fkey"), "role", type_="foreignkey")
    op.alter_column(
        "role", "type", existing_type=sa.Text(), type_=sa.VARCHAR(length=5), existing_nullable=False
    )
    op.drop_table("lk_role")
    # ### end Alembic commands ###
