name: CI - App

on:
  push:
    branches:
      - main
    paths:
      - app/**
      - .github/workflows/ci-app.yml
  pull_request:
    paths:
      - app/**
      - .github/workflows/ci-app.yml

defaults:
  run:
    working-directory: ./app

jobs:
  # As an enhancement, it is possible to share the built docker image and share
  # it across jobs as described in:
  # https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts#passing-data-between-jobs-in-a-workflow
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run format check
        run: make format-check

      - name: Run linting
        run: make lint
  security-scan:
    name: Security scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run security linting
        run: make lint-security
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start tests
        run: |
          make test-audit
          make test-coverage
