name: Template API Checks

on:
  push:
    branches:
      - main
    paths:
      - app/**
      - .github/workflows/api-checks.yml
  pull_request:
    paths:
      - app/**
      - .github/workflows/api-checks.yml

defaults:
  run:
    working-directory: ./app

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run format check
        run: make format-check

      - name: Run linting
        run: make lint

  lint-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run security linting
        run: make lint-security

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start tests
        run: make test-coverage
