# Update OpenAPI docs so that they remain up to date with the application
name: Update OpenAPI Docs

on:
  pull_request:
    paths:
      - app/**
      - Makefile
      - .github/workflows/ci-openapi.yml

defaults:
  run:
    working-directory: ./app

# Only trigger run one update of the OpenAPI spec at a time on the branch.
# If new commits are pushed to the branch, cancel in progress runs and start
# a new one.
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true


jobs:
  update-openapi-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Checkout the feature branch associated with the pull request
          ref: ${{ github.head_ref }}

      - name: Update OpenAPI spec
        run: make openapi-spec

      - name: Push changes
        run: |
          git config user.name nava-platform-bot
          git config user.email platform-admins@navapbc.com
          git add --all
          # Commit changes (if no changes then no-op)
          git diff-index --quiet HEAD || git commit -m "Update OpenAPI spec"
          git push
